fork_me_url: https://github.com/civictechto/people-list-parser
app_name: People List Parser Demo
org_name: Civic Tech Toronto
org_url: http://civictech.ca
gsheet:
  key: 1LCVxEXuv70R-NozOwhNxZFtTZUmn1FLMPVD5wgIor9o
  sheet_id: 642523045
